export const PEER_CONNECTION_UPDATE = 'PEER_CONNECTION_UPDATE';
export const LOCAL_STREAM_UPDATE = 'LOCAL_STREAM_UPDATE';
export const REMOTE_STREAM_UPDATE = 'REMOTE_STREAM_UPDATE';
export const ROOM_DIALOG_UPDATE = 'ROOM_DIALOG_UPDATE';
export const ROOM_ID_UPDATE = 'ROOM_ID_UPDATE';

export const OPEN_CAMERA = 'OPEN_CAMERA';
export const OPEN_CAMERA_ERROR = 'OPEN_CAMERA_ERROR';
export const JOIN_ROOM_ERROR = 'JOIN_ROOM_ERROR';
export const RECEIVED_REMOTE_TRACK = 'RECEIVED_REMOTE_TRACK';
export const INITIALIZE_PEER_CONNECTION = 'INITIALIZE_PEER_CONNECTION';
export const HANG_UP = 'HANG_UP';
export const TOGGLE_MUTE = 'TOGGLE_MUTE';
export const TOGGLE_DEAFEN = 'TOGGLE_DEAFEN';
export const TOGGLE_VIDEO = 'TOGGLE_VIDEO';
export const ADD_SNAPSHOT = 'ADD_SNAPSHOT';
export const CALL_ENDED = 'CALL_ENDED';